# Generated by Django 5.1.7 on 2025-03-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_lessons.courses'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_lessons.student'),
        ),
    ]
