# Generated by Django 5.1.7 on 2025-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_lessons', '0002_alter_review_courses_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answers_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name_assignment_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_name_ky',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='name_exam_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='content_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='name_lessons_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='name_questions_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ky',
            field=models.TextField(null=True),
        ),
    ]
